# Generated by Django 2.0.1 on 2018-01-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0023_auto_20180126_2005'),
        ('e_reg', '0002_contactcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='ContactCard',
        ),
    ]
