# Generated by Django 2.0.1 on 2018-01-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='author',
            new_name='user',
        ),
    ]
