# Generated by Django 2.0.1 on 2018-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0005_auto_20180126_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_postcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
