# Generated by Django 2.0.1 on 2018-01-26 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0007_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.ForeignKey(on_delete='CASCADE', related_name='emailfield', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
