# Generated by Django 2.0.1 on 2018-01-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0010_auto_20180126_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
