# Generated by Django 2.0.1 on 2018-01-27 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0012_auto_20180127_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(default='', max_length=20)),
                ('address_street', models.CharField(default='', max_length=255)),
                ('address_postcode', models.CharField(default='', max_length=10)),
                ('address_city', models.CharField(default='', max_length=30)),
                ('address_country', models.CharField(default='', max_length=30)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useremail', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
