# Generated by Django 2.0.1 on 2018-01-29 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0016_auto_20180129_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone_number', models.CharField(default='', max_length=20)),
                ('address_street', models.CharField(default='', max_length=255)),
                ('address_postcode', models.CharField(default='', max_length=10)),
                ('address_city', models.CharField(default='', max_length=30)),
                ('address_country', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('e_reg.user',),
        ),
    ]
