# Generated by Django 2.0.1 on 2018-01-30 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0023_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('e_reg.user',),
        ),
        migrations.AlterModelOptions(
            name='hotelproperty',
            options={'verbose_name_plural': 'Hotel Properties'},
        ),
    ]
