# Generated by Django 2.0.1 on 2018-02-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0024_auto_20180130_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestuser',
            options={'ordering': ['-id']},
        ),
    ]
