# Generated by Django 2.0.1 on 2018-02-04 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0025_auto_20180203_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='e_reg.Preferences')),
                ('choices', models.CharField(max_length=255)),
            ],
            bases=('e_reg.preferences',),
        ),
        migrations.AddField(
            model_name='preferences',
            name='guestuser',
            field=models.ForeignKey(on_delete='CASCADE', to='e_reg.GuestUser'),
        ),
    ]
