# Generated by Django 2.0.1 on 2018-02-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0027_auto_20180205_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='guestuser',
        ),
        migrations.RemoveField(
            model_name='roompreferences',
            name='preferences_ptr',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
        migrations.DeleteModel(
            name='RoomPreferences',
        ),
    ]
