# Generated by Django 2.0.1 on 2018-02-05 03:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0028_auto_20180205_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Floor', (('HI', 'High Floor'), ('LO', 'Low Floor'))), ('Elevator', (('AE', 'Away from Elevator'), ('NE', 'Near to Elevator')))], default='', max_length=14),
        ),
    ]
