# Generated by Django 2.0.1 on 2018-02-05 03:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0029_guestuser_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Floor', (('HI', 'High Floor'), ('LO', 'Low Floor'))), ('Elevator', (('AE', 'Away from Elevator'), ('NE', 'Near to Elevator')))], max_length=14),
        ),
    ]
