# Generated by Django 2.0.1 on 2018-02-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0030_auto_20180205_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='choices',
        ),
        migrations.AddField(
            model_name='guestuser',
            name='room_level',
            field=models.CharField(choices=[('Floor', (('HI', 'High Floor'), ('LO', 'Low Floor'))), ('Elevator', (('AE', 'Away from Elevator'), ('NE', 'Near to Elevator')))], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
