# Generated by Django 2.0.1 on 2018-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0032_remove_guestuser_room_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='room_preferences',
            field=models.CharField(choices=[('Floor', (('HI', 'High Floor'), ('LO', 'Low Floor'))), ('Elevator', (('AE', 'Away from Elevator'), ('NE', 'Near to Elevator')))], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
