# Generated by Django 2.0.1 on 2018-02-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0033_guestuser_room_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestuser',
            name='room_preferences',
            field=models.CharField(blank=True, choices=[('Floor', (('HI', 'High Floor'), ('LO', 'Low Floor'))), ('Elevator', (('AE', 'Away from Elevator'), ('NE', 'Near to Elevator')))], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(choices=[('NL', 'Netherlands'), ('TR', 'Turkey'), ('UK', 'United Kingdom')], default='', max_length=60),
        ),
    ]
