# Generated by Django 2.0.1 on 2018-02-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0034_auto_20180206_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_country',
            field=models.CharField(choices=[('Netherlands', 'Netherlands'), ('Turkey', 'Turkey'), ('United Kingdom', 'United Kingdom')], default='', max_length=60),
        ),
    ]
