# Generated by Django 2.0.1 on 2018-02-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0035_auto_20180206_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestuser',
            name='room_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='room_preferences',
            field=models.CharField(blank=True, choices=[('High Floor', 'High Floor'), ('Low Floor', 'Low Floor')], max_length=100),
        ),
    ]
