# Generated by Django 2.0.1 on 2018-02-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0037_auto_20180209_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
