# Generated by Django 2.0.1 on 2018-02-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0038_hotelmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel_membership',
            field=models.ForeignKey(blank=True, default=1, on_delete='CASCADE', to='e_reg.HotelMembership'),
            preserve_default=False,
        ),
    ]
