# Generated by Django 2.0.1 on 2018-02-09 06:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0039_user_hotel_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hotel_membership',
        ),
        migrations.AddField(
            model_name='user',
            name='hotel_memberships',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Accor', 'LeClub Accor Hotels'), ('Hilton', 'HHonors'), ('Marriott', 'Marriott Rewards'), ('Inter Continental', 'IHG Rewards Club')], max_length=500),
        ),
        migrations.DeleteModel(
            name='HotelMembership',
        ),
    ]
