# Generated by Django 2.0.1 on 2018-02-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0041_remove_user_hotel_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.CharField(max_length=100)),
            ],
        ),
    ]
