# Generated by Django 2.0.1 on 2018-02-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0042_hotelmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hotel_memberships',
            field=models.ManyToManyField(blank=True, to='e_reg.HotelMembership'),
        ),
    ]
