# Generated by Django 2.0.1 on 2018-02-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0044_auto_20180209_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hotel_memberships',
        ),
    ]
