# Generated by Django 2.0.1 on 2018-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0045_remove_user_hotel_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_name', models.CharField(max_length=100)),
                ('membership_number', models.IntegerField(default='')),
                ('guestuser', models.ForeignKey(on_delete='CASCADE', to='e_reg.GuestUser')),
            ],
        ),
    ]
