# Generated by Django 2.0.1 on 2018-02-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0046_hotelmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmembership',
            name='chain_name',
        ),
        migrations.AddField(
            model_name='hotelmembership',
            name='membership_programme_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelmembership',
            name='membership_number',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
