# Generated by Django 2.0.1 on 2018-02-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0047_auto_20180209_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmembership',
            name='membership_programme_name',
            field=models.CharField(blank=True, choices=[('HHonors', 'Hilton - HHonors'), ('IHG Rewards Club', 'Inter Continental - IHG Rewards Club'), ('LeClub Accor Hotels', 'Accor - LeClub Accor Hotels'), ('Marriott Rewards', 'Marriott - Marriott Rewards')], max_length=100),
        ),
    ]
