# Generated by Django 2.0.1 on 2018-02-20 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0050_auto_20180209_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='g_avatar',
        ),
    ]
