# Generated by Django 2.0.1 on 2018-02-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0051_auto_20180220_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='g_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
