# Generated by Django 2.0.1 on 2018-02-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0053_auto_20180220_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='g_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
