# Generated by Django 2.0.1 on 2018-11-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0055_auto_20181108_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproperty',
            name='membership',
            field=models.CharField(choices=[('HHonors', 'Hilton - HHonors'), ('IHG Rewards Club', 'Inter Continental - IHG Rewards Club'), ('LeClub Accor Hotels', 'Accor - LeClub Accor Hotels'), ('Marriott Rewards', 'Marriott - Marriott Rewards')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelproperty',
            name='name',
            field=models.CharField(blank=True, choices=[('DoubleTree by Hilton - Centraal Station', 'DoubleTree by Hilton - Centraal Station'), ('Sofitel Legend The Grand Amsterdam', 'Sofitel Legend The Grand Amsterdam')], max_length=255),
        ),
    ]
