# Generated by Django 2.0.1 on 2018-11-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_reg', '0056_auto_20181108_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelproperty',
            name='membership',
            field=models.CharField(blank=True, choices=[('HHonors', 'Hilton - HHonors'), ('IHG Rewards Club', 'Inter Continental - IHG Rewards Club'), ('LeClub Accor Hotels', 'Accor - LeClub Accor Hotels'), ('Marriott Rewards', 'Marriott - Marriott Rewards')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hotelproperty',
            name='room_features',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
